const games: Game[] = [
  {
    id: "6",
    name: "Flabby Physics",
    poster: "/games_images/flappy_physics.png",
    flashFile: "/games/flabby_physics.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["casino", "arcade"],
  },
  {
    id: "0",
    name: "4 Table Poker",
    poster: "/games_images/poker.png",
    flashFile: "/games/POKER-FACE-UP.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["casino", "featured"],
  },
  {
    id: "10",
    name: "Race Walk",
    poster: "/games_images/racewalk.png",
    flashFile: "/games/racewalk.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["racing"],
  },
  {
    id: "13",
    name: "Age of War",
    poster: "/games_images/age_of_war.png",
    flashFile: "/games/Age_of_War.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["action"],
  },
  {
    id: "14",
    name: "Dice Wars",
    poster: "/games_images/dice_wars.png",
    flashFile: "/games/Dice-Wars.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["casino"],
  },
  {
    id: "16",
    name: "Get Lost",
    poster: "/games_images/get_lost.png",
    flashFile: "/games/Get Lost.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["adventure", "strategy", "arcade"],
  },
  {
    id: "17",
    name: "Ice Punch",
    poster: "/games_images/ice_punch.png",
    flashFile: "/games/Ice Punch.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["arcade"],
    featured: true,
  },
  {
    id: "18",
    name: "Missile",
    poster: "/games_images/missile.png",
    flashFile: "/games/Missile.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["arcade"],
  },
  {
    id: "20",
    name: "Coaster Racer",
    poster: "/games_images/coaster_racer.png",
    flashFile: "/games/coaster-racer-714079f9.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["racing"],
  },
  {
    id: "21",
    name: "Flash Racer",
    poster: "/games_images/flash_racer.png",
    flashFile: "/games/flash-racer-1321817f.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["racing"],
  },
];

export const sampleGames: Game[] = [...games];
