const games: Game[] = [
  {
    id: "0",
    name: "4 Table Poker",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/POKER-FACE-UP.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["casino", "featured"],
  },
  {
    id: "6",
    name: "flabby_physics",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/flabby_physics.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["casino", "arcade"],
  },
  {
    id: "10",
    name: "racewalk",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/racewalk.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["racing"],
  },
  {
    id: "13",
    name: "Age_of_War",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/Age_of_War.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["action"],
  },
  {
    id: "14",
    name: "Dice-Wars",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/Dice-Wars.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["casino"],
  },
  {
    id: "16",
    name: "Get Lost",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/Get Lost.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["adventure", "strategy", "arcade"],
  },
  {
    id: "17",
    name: "Ice Punch",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/Ice Punch.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["arcade"],
    featured: true,
  },
  {
    id: "18",
    name: "Missile",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/Missile.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["arcade"],
  },
  {
    id: "20",
    name: "Coaster Racer",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/coaster-racer-714079f9.swf",
    description: "Test your luck and skill in this poker game.",
    featured: true,
    categories: ["racing"],
  },
  {
    id: "21",
    name: "Flash Racer",
    poster: "https://image.tmdb.org/t/p/w500//2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    flashFile: "/games/flash-racer-1321817f.swf",
    description: "Test your luck and skill in this poker game.",
    categories: ["racing"],
  },
];

export const sampleGames: Game[] = [...games];
